/*
 * gen-puzzles.js — sweep for Tyranny puzzles and write puzzles/puzzles.json.
 *
 *   node tools/gen-puzzles.js [--games N] [--seed N] [--bias 0.5] [--out path]
 *   node tools/gen-puzzles.js --inline        fill the PUZZLE-DATA markers in
 *                                             src/tyranny.html from puzzles.json
 *
 * --inline is provided but NEVER run by the generating seat; the orchestrator
 * runs it once after the merge, when the markers exist.
 *
 * Both predicates are DEPTH-FREE. No search, no engine scoring, no think().
 * think()'s root loop raises alpha as it goes, so its per-move _r values are
 * upper bounds on inferior moves rather than scores — 68 of 71 were wrong on one
 * measured position. Nothing here needs it.
 *
 * Search: check-biased playout from startState(). With probability `bias`, pick
 * uniformly among moves that give check; otherwise uniformly among all legal
 * moves. Seeded, so a given --seed reproduces byte-identical output.
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const OUT_DEFAULT = path.join(ROOT, 'puzzles', 'puzzles.json');
const SRC = path.join(ROOT, 'src', 'tyranny.html');
/*
 * The markers are JS BLOCK COMMENTS, not HTML comments, because they sit INSIDE
 * the page's single <script> block — it opens at src/tyranny.html:422 and closes
 * at :1665, and the markers are at 903-904, just after the GAME / UI banner.
 *
 * That placement dictates the payload shape: a bare assignment with NO tags.
 * Emitting a nested <script>...</script> here would make the inner </script>
 * terminate the OUTER block early and kill the whole page.
 */
const MARK_BEGIN = '/* PUZZLE-DATA-BEGIN */';
const MARK_END = '/* PUZZLE-DATA-END */';

/*
 * --inline is handled BEFORE the engine is required, and that ordering is the
 * fix, not a style choice.
 *
 * tests/engine.js is generated by tests/extract.js and is gitignored, so it does
 * not exist in a fresh checkout. The orchestrator runs `--inline` once after the
 * merge — exactly the moment engine.js is most likely absent — and a top-level
 * require made that command die with MODULE_NOT_FOUND before doing anything.
 * inline() needs only fs, path and JSON, so it runs here and exits.
 */
if (require.main === module && process.argv.includes('--inline')) {
  inline(arg('--src', null), arg('--out', null));
  process.exit(0);
}

const E = require('./../tests/engine.js');
const { startState, legal, apply, inCheck, fen, san, sqName } = E;
const { toFen } = require('./fen-write.js');
/* trySurvival lives with the seeder because that is where it is applied at
   scale. It is imported rather than copied so the two tools cannot drift, and
   requiring the file runs nothing: its CLI is behind require.main === module. */
const { trySurvival } = require('./lichess-seed.js');
/* The continuation a multi-move puzzle is played through. Called for EVERY
   multistep entry this file builds, from the sweep and from the Lichess seed
   alike, so there is one place that decides what a line is. It used to be a
   separate tool that edited puzzles.json in place; this generator knew nothing
   about it, so regenerating the file would have reverted the schema and dropped
   every line. */
const { lineFor } = require('./line.js');

/* The schema this generator WRITES, and the number tests/puzzles.js compares
   against the committed file. It is a named constant rather than a literal in
   the document so the generator and the data it produced cannot disagree
   without a test noticing. 5 added `line` (the continuation of a multi-move
   puzzle) and let a multistep puzzle carry a Lichess `source`. */
const SCHEMA = 5;

/* ------------------------------ predicates ------------------------------ */

function isMate(T) {
  return legal(T, true).length === 0 && inCheck(T, T.turn);
}

function matesIn2(S, m) {
  if (isMate(apply(S, m))) return true;
  const T = apply(S, m);
  const rep = legal(T, true);
  if (rep.length === 0) return false;
  return rep.every(function (r) {
    const U = apply(T, r);
    return legal(U, true).some(function (x) { return isMate(apply(U, x)); });
  });
}

/* ESCAPE: mate under standard rules, survivable under Tyranny.
   Every tyranny-legal move is then a self-capture by construction — the two
   move sets differ by exactly the self-captures — but the validator re-checks
   that rather than trusting it. */
function tryEscape(S) {
  if (!inCheck(S, S.turn)) return null;
  const ms = legal(S, true);
  if (ms.length < 1) return null;
  if (legal(S, false).length !== 0) return null;
  return ms;
}

/* TACTICAL: exactly one self-capture mates in 1, nothing else mates in 1, and
   no ordinary move forces mate within two.

   Check order is the whole performance story. The self-mate scan is one legal()
   per candidate and rejects ~99% of positions; matesIn2 is a nested sweep and
   runs only on what survives. Cheap test first, expensive test last. */
function tryTactical(S) {
  const ms = legal(S, true);
  let sole = null, n = 0;
  for (const m of ms) {
    if (m.kind !== 'self') continue;
    if (isMate(apply(S, m))) { n++; if (n > 1) return null; sole = m; }
  }
  if (n !== 1) return null;
  for (const m of ms) {
    if (m.kind === 'self') continue;
    if (isMate(apply(S, m))) return null;          // an ordinary move also mates
  }
  for (const m of ms) {                             // expensive, and last
    if (m.kind === 'self') continue;
    if (matesIn2(S, m)) return null;
  }
  return { sole: sole, ms: ms };
}

/* MULTISTEP (goal-tree M3-T1): exactly one self-capture FORCES mate within
   three plies -- after it, EVERY opponent reply leaves the mover a mate-in-1 --
   and it is deliberately NOT a one-mover.

   Three clauses, and the last two are what make the family mean anything:

     1. At least one self-capture is legal at all.
     2. REJECTION (AC2). No self-capture is itself mate-in-1. Without this the
        family collapses into 'tactical' wearing a different label, and the
        puzzle is solvable without seeing past the first move. An ordinary
        mate-in-1 is rejected for the same reason from the other side: it would
        solve the position with no execution at all.
     3. NECESSITY (AC3). No ORDINARY move forces mate in the same three plies.
        Without this the execution is merely sufficient, not necessary, and
        'you had to execute your own piece' is a claim the position does not
        support.

   Depth-free, like every other predicate here: legal(), apply() and inCheck()
   only, exhaustively enumerated. No search, no scoring, no think(). That is
   what makes a --seed reproduce a set exactly.

   Note on the order of the loops: the two mate-in-1 scans are one legal() per
   candidate and throw out the overwhelming majority of positions. matesIn2 is a
   nested sweep, so it runs only on what survives. Cheap test first. */
function tryMultistep(S) {
  const ms = legal(S, true);
  const selfs = [], ords = [];
  for (const m of ms) (m.kind === 'self' ? selfs : ords).push(m);
  if (!selfs.length) return null;

  for (const m of selfs) if (isMate(apply(S, m))) return null;   // clause 2
  for (const m of ords) if (isMate(apply(S, m))) return null;    // clause 2, other side

  /* Past this point nothing is mate-in-1, so matesIn2's own first clause can
     never fire and it means exactly 'every reply has a mating answer'. */
  let sole = null, n = 0;
  for (const m of selfs) {
    if (matesIn2(S, m)) { n++; if (n > 1) return null; sole = m; }
  }
  if (n !== 1) return null;

  for (const m of ords) if (matesIn2(S, m)) return null;         // clause 3, expensive, last

  return { sole: sole, ms: ms, selfs: selfs, ords: ords };
}

/* RESTRAINT (goal-tree M3-T2): the position where executing your own piece is
   the WRONG answer. An ordinary move wins outright, a self-capture is sitting
   right there, and no self-capture matches the ordinary move.

   'No self-capture achieves the same' is read STRICTLY, and that is a
   deliberate strengthening of the proposal in the goal tree, which said only
   that no self-capture should be mate-in-1. A self-capture that forces mate one
   move later is not wrong, merely slower -- and a puzzle whose lesson is 'the
   execution also wins, just less quickly' does not teach restraint. So both are
   excluded: no self-capture mates in 1, and none forces mate within three
   plies either. Executing here is simply not a winning idea.

   The solution is every ordinary move that mates at once. The self-captures are
   the decoys, because they ARE the trap. */
function tryRestraint(S) {
  const ms = legal(S, true);
  const selfs = [], ords = [];
  for (const m of ms) (m.kind === 'self' ? selfs : ords).push(m);
  if (!selfs.length) return null;                 // no temptation, no lesson (AC1)

  const wins = ords.filter(function (m) { return isMate(apply(S, m)); });
  if (!wins.length) return null;

  for (const m of selfs) if (isMate(apply(S, m))) return null;   // an execution mates too
  for (const m of selfs) if (matesIn2(S, m)) return null;        // ...or forces it a move later

  return { wins: wins, ms: ms, selfs: selfs, ords: ords };
}

/* ------------------------------ plumbing ------------------------------ */

function mulberry32(a) {
  return function () {
    a |= 0; a = (a + 0x6D2B79F5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const uci = function (m) { return sqName(m.from) + sqName(m.to) + (m.promo || ''); };
const plain = function (m) { return { from: m.from, to: m.to, promo: m.promo || null }; };

/* Difficulty is a stated rule, not a feel: how large a set you must reject to
   find the answer.
     escape   — forced (one legal move) is 1; a choice among several is 2.
     tactical — the legal-move count IS that set. Threshold 35 comes from the
                measured distribution over a 108k-position sweep: tacticals run
                26..67 legal moves, median 43. An earlier guess of <=20 was
                unreachable — zero of 25 tacticals fell under it, so every
                tactical scored 3 and the level was decorative.
   The orchestrator's pre-run fixture contained no difficulty-2 example at all,
   so no reader had ever exercised that branch. Both families can now produce
   one. */
function escapeDifficulty(ms) { return ms.length === 1 ? 1 : 2; }
function tacticalDifficulty(ms) { return ms.length <= 35 ? 2 : 3; }
/* multistep — the same "size of the set you must reject" rule, floored at 2:
   no multistep can be a 1, because the family REJECTS every one-mover by
   construction, so you always have to see three plies ahead.
   restraint — same rule again, but the set that matters is the one you must
   refuse, so the count of legal self-captures is the second axis. A position
   waving five executions at you is a harder refusal than one waving a single
   one. Thresholds below come from the measured distribution of the real run
   and are printed by --stats. */
function multistepDifficulty(ms) { return ms.length <= 35 ? 2 : 3; }
function restraintDifficulty(ms, selfs) {
  if (ms.length <= 30 && selfs <= 2) return 1;
  if (ms.length <= 45 || selfs <= 3) return 2;
  return 3;
}

const RATIONALE = {
  /* RETIRED 2026-09-17. The escape family could not be hard: it listed EVERY
     legal move as a correct answer, so it had zero wrong answers by
     construction - "you are mated under normal rules, now play anything". Its
     replacement is survival, which keeps the setup and adds a way to be wrong.
     Kept here as a string only, because a schema-3 file still in someone's
     browser cache can still name it. */
  escape: 'Checkmate under standard rules. Only an execution of your own piece survives.',
  survival: 'Checkmate under standard rules, and the variant offers several ways out. Only one of them is still alive after the reply; the rest are legal, look no different, and lose.',
  tactical: 'Executing your own piece mates at once, and no ordinary move forces mate within two.',
  multistep: 'One execution forces mate in two: after it, every reply the opponent has still runs into mate. No execution mates at once, and no ordinary move forces mate either, so seeing one move ahead is not enough and skipping the execution does not win.',
  restraint: 'The execution is the trap. An ordinary move mates at once and no self-capture matches it, so taking your own piece here is simply the wrong idea.'
};

/* Up to three legal moves that are NOT the solution. Checks and captures first,
   because a plausible distractor is the point. The solution is excluded by key,
   not by identity — the committed fixture shipped a decoy that WAS its solution
   and the validator caught it, so this is belt and braces. */
function pickDecoys(S, ms, solutions) {
  const banned = new Set(solutions.map(function (m) { return m.from + ':' + m.to + ':' + (m.promo || '-'); }));
  const cand = ms.filter(function (m) { return !banned.has(m.from + ':' + m.to + ':' + (m.promo || '-')); });
  const scored = cand.map(function (m) {
    const T = apply(S, m);
    let s = 0;
    if (inCheck(T, T.turn)) s += 4;
    if (m.cap) s += 2;
    if (m.kind === 'self') s += 1;
    return { m: m, s: s };
  });
  scored.sort(function (a, b) { return b.s - a.s || uci(a.m).localeCompare(uci(b.m)); });
  return scored.slice(0, 3).map(function (x) { return { uci: uci(x.m), san: san(S, x.m, true) }; });
}

/* For a RESTRAINT the decoys are not garnish, they ARE the trap: every legal
   self-capture, most attractive first. Everywhere else they are ordinary
   distractors. Escape gets none because every legal move is a solution, so
   there is nothing left to be a decoy. */
function pickTemptations(S, ms, solutions) {
  const selfs = ms.filter(function (m) { return m.kind === 'self'; });
  const scored = selfs.map(function (m) {
    const T = apply(S, m);
    let sc = 0;
    if (inCheck(T, T.turn)) sc += 4;                       // a check looks forcing
    if (m.cap) sc += ({ q: 3, r: 2, b: 1, n: 1, p: 0 })[m.cap[1]] || 0;
    return { m: m, s: sc };
  });
  scored.sort(function (a, b) { return b.s - a.s || uci(a.m).localeCompare(uci(b.m)); });
  return scored.slice(0, 3).map(function (x) { return { uci: uci(x.m), san: san(S, x.m, true) }; });
}

function buildEntry(id, family, S, solutionMoves, ms, std) {
  const sols = solutionMoves.map(plain);
  const selfCount = ms.filter(function (m) { return m.kind === 'self'; }).length;
  const decoys = family === 'escape' ? []
    : family === 'restraint' ? pickTemptations(S, ms, solutionMoves)
    : pickDecoys(S, ms, solutionMoves);
  const diff = family === 'escape' ? escapeDifficulty(ms)
    : family === 'tactical' ? tacticalDifficulty(ms)
    : family === 'multistep' ? multistepDifficulty(ms)
    : restraintDifficulty(ms, selfCount);
  /* A multistep puzzle is only a multistep puzzle if the player is asked for the
     second move, so the line is not optional garnish: failing to build one is a
     defect in the predicate or the position and stops the run. Emitting a
     multistep record WITHOUT a line is exactly the bug this field fixes --
     round 2 shipped that, with every data check green. */
  let L = null;
  if (family === 'multistep') {
    const r = lineFor(S, solutionMoves[0]);
    if (!r.line) throw new Error('multistep ' + id + ' has no line: ' + r.why + ' -- ' + toFen(S));
    L = r.line;
  }
  return {
    id: id,
    family: family,
    fen: toFen(S),
    sideToMove: S.turn,
    legalMoveCount: ms.length,
    /* Schema 3. Re-derived from the FEN by tests/puzzles.js like every other
       number here, so it is a checked claim rather than a stored assertion.
       It is what makes "the temptation is real" a fact about the position. */
    selfCaptureCount: selfCount,
    soleLegalMove: ms.length === 1,
    standardLegalMoveCount: std,
    solutions: sols,
    solutionsUci: solutionMoves.map(uci),
    solutionsSan: solutionMoves.map(function (m) { return san(S, m, true); }),
    /* Present only on a multistep entry; spread so the other families keep the
       exact key set they always had. Placed beside the answer it continues. */
    ...(L ? { line: L } : {}),
    decoys: decoys,
    rationale: RATIONALE[family],
    difficulty: diff
  };
}

/* ------------------------------ the sweep ------------------------------ */

/* The four families in PRECEDENCE order, cheapest predicate first.

   Five of the six pairs are disjoint by construction and need no ordering:
   tactical demands exactly one self-capture mate-in-1, multistep demands none,
   and restraint demands an ordinary mate-in-1 that both of the others reject.

   ESCAPE AND MULTISTEP ARE NOT DISJOINT IN THEORY — a position in check with no
   ordinary moves at all satisfies multistep's necessity clause vacuously — which
   is why escape runs first. But that overlap has never been OBSERVED: zero of
   the 34 shipped escapes satisfy the multistep predicate, and a sweep of 409,622
   constructed endgames containing 1,532 escapes produced none either. An earlier
   version of this comment called the ordering "load-bearing, not merely
   cheaper", which overstated it — today it bears nothing, and it is kept as a
   forward guard against a loosened predicate or a fifth family. tests/puzzles.js
   measures the overlap as a NUMBER on every run rather than leaving a branch
   that cannot fire looking like assurance. */
const FAMILIES = [
  /* escape was here and is retired - see RATIONALE above. tryEscape() itself
     stays exported and is still used by tests/puzzles.js, because SURVIVAL is a
     strict subset of it: every survival position is a standard-rules checkmate
     that the variant reopens. Dropping the predicate would remove the check
     that a survival puzzle really is one. */
  { name: 'tactical',  prefix: 'tac', run: tryTactical,  sols: function (r) { return [r.sole]; } },
  { name: 'restraint', prefix: 'res', run: tryRestraint, sols: function (r) { return r.wins; } },
  { name: 'multistep', prefix: 'mul', run: tryMultistep, sols: function (r) { return [r.sole]; } }
];

function sweep(opts) {
  const rnd = mulberry32(opts.seed);
  const seen = new Set();
  const found = {};
  const predMs = {};
  FAMILIES.forEach(function (F) { found[F.name] = []; predMs[F.name] = 0; });
  let positions = 0, games = 0;
  const t0 = Date.now();
  const enough = function () {
    return FAMILIES.every(function (F) { return found[F.name].length >= opts.target; });
  };

  for (let g = 0; g < opts.games; g++) {
    games++;
    let S = startState();
    for (let ply = 0; ply < 200; ply++) {
      const ms = legal(S, true);
      if (!ms.length) break;
      positions++;

      const f = toFen(S);
      if (!seen.has(f)) {
        seen.add(f);
        for (let i = 0; i < FAMILIES.length; i++) {
          const F = FAMILIES[i];
          const a = Date.now();
          const r = F.run(S);
          predMs[F.name] += Date.now() - a;
          if (r) {
            found[F.name].push(buildEntry(
              F.prefix + '-' + String(found[F.name].length + 1).padStart(4, '0'),
              F.name, S, F.sols(r), ms, legal(S, false).length));
            break;                       // precedence: first match wins
          }
        }
      }

      const checks = ms.filter(function (m) { const T = apply(S, m); return inCheck(T, T.turn); });
      const pool = (checks.length && rnd() < opts.bias) ? checks : ms;
      S = apply(S, pool[(rnd() * pool.length) | 0]);

      if (enough()) break;
    }
    if (enough()) break;
    if (Date.now() - t0 > opts.msBudget) break;
  }
  return { found: found, predMs: predMs, positions: positions, games: games,
           ms: Date.now() - t0, unique: seen.size };
}

/* ------------------------------ --inline ------------------------------ */

/* srcPath/docPath are overridable so this path can be TESTED without editing the
   real src/tyranny.html, which the generating seat is not allowed to touch.
   Defaults are the real files, so the orchestrator's plain `--inline` is
   unchanged. */
function inline(srcPath, docPath) {
  const SRCF = srcPath || SRC;
  const DOCF = docPath || OUT_DEFAULT;
  if (!fs.existsSync(DOCF)) { console.error('inline: ' + DOCF + ' does not exist'); process.exit(1); }
  const doc = fs.readFileSync(DOCF, 'utf8');
  let src;
  try { src = fs.readFileSync(SRCF, 'utf8'); }
  catch (e) { console.error('inline: cannot read ' + SRCF); process.exit(1); }

  const a = src.indexOf(MARK_BEGIN), b = src.indexOf(MARK_END);
  if (a < 0 || b < 0 || b < a) {
    console.error('inline: PUZZLE-DATA markers not found in ' + SRCF + '.');
    console.error('  Expected, on their own lines, in this order:');
    console.error('    ' + MARK_BEGIN);
    console.error('    ' + MARK_END);
    console.error('  Nothing was written. This is not a generator defect: the markers are');
    console.error('  added by the UI lane, and --inline is meant to run after that merge.');
    process.exit(1);
  }
  /* Keep the "</" escape build.js uses. It is still load-bearing even with no
     tags of our own: a literal </script> arriving inside a JSON string would
     close the page's outer block just the same. */
  const json = JSON.stringify(JSON.parse(doc)).replace(/<\//g, '<\\/');

  /* A bare assignment. No <script>, no </script> — see the marker comment above. */
  const payload = MARK_BEGIN + '\nwindow.TYRANNY_PUZZLES = ' + json + ';\n' + MARK_END;

  /* Refuse rather than corrupt: if the payload could itself contain the end
     marker, the next run's indexOf would land inside the data and the replace
     would eat part of the page. No current field can produce it; the check
     costs nothing and removes the class. */
  if (json.indexOf(MARK_END) >= 0) {
    console.error('inline: refusing to write — the payload contains the end marker ' + MARK_END);
    process.exit(1);
  }

  /* Replaces the whole span INCLUDING both markers, so re-running replaces the
     block rather than nesting inside it. */
  const next = src.slice(0, a) + payload + src.slice(b + MARK_END.length);
  fs.writeFileSync(SRCF, next, 'utf8');
  console.log('inline: wrote ' + JSON.parse(doc).puzzles.length + ' puzzles into ' +
              path.basename(SRCF) + ' between the PUZZLE-DATA markers');
}

/* ------------------------- Lichess-seeded multistep ------------------------- */

/* Turn the seed tools/lichess-multistep.js wrote into finished entries.
 *
 * The seed supplies a POSITION and where it came from, and nothing else is
 * trusted. The solution, the line, the decoys and the difficulty are recomputed
 * here from the FEN by this file's own predicate, and the seed's recorded answer
 * is used only to CONTRADICT that derivation if the two ever disagree. A seed
 * that no longer satisfies the predicate throws: dropping it quietly would make
 * a regeneration look like it worked while shipping fewer puzzles than the seed
 * promised. The same discipline as the survival family.
 *
 * Ids are `mls-<lichess puzzle id>-<ply>`, built from the position's own
 * identity and not from a running number. Solved-state is stored in the player's
 * browser keyed by id, so an id has to keep meaning the same position. A running
 * number (`mls-0001`, which is what this first used) renumbers whenever the seed
 * is re-mined with different parameters -- another row bound, another reply
 * filter -- and would silently point a returning player's solved marks at
 * different puzzles. (Found by deepcheck: the comment here promised exactly the
 * stability the code did not deliver.) The `sur-` ids are still running numbers;
 * they predate this and carry the same exposure.
 *
 * Returns entries with no sweep FEN check -- the caller has the sweep and does
 * that comparison, which is the one check that needs it. */
function deriveMultistepSeeds(seed) {
  const out = [];
  const seen = new Set();
  const ids = new Set();
  (seed.puzzles || []).forEach(function (p, i) {
    const tag = 'multistep seed ' + (p.source && p.source.id ? p.source.id : '#' + (i + 1));
    const S = fen(p.fen);
    const r = tryMultistep(S);
    if (!r) throw new Error(tag + ': the position no longer satisfies the predicate -- ' + p.fen);
    if (uci(r.sole) !== p.solutionUci) {
      throw new Error(tag + ': the seed says ' + p.solutionUci + ', the predicate says ' + uci(r.sole));
    }
    const f = toFen(S);
    if (seen.has(f)) throw new Error(tag + ': the same position appears twice in the seed -- ' + f);
    seen.add(f);
    const src = p.source;
    if (!src || typeof src.id !== 'string' || !src.id || !Number.isInteger(src.ply) || src.ply < 0) {
      throw new Error(tag + ': needs source.id and a non-negative integer source.ply, because the puzzle id is built from them');
    }
    const id = 'mls-' + src.id + '-' + src.ply;
    if (ids.has(id)) throw new Error(tag + ': the id ' + id + ' appears twice in the seed');
    ids.add(id);
    const e = buildEntry(id, 'multistep', S, [r.sole], r.ms, legal(S, false).length);
    /* CC0 asks for no attribution. The link is here because a position a reader
       can trace back to a real game is worth more than one that appeared from
       nowhere. The rating is the Lichess rating of the STANDARD puzzle the
       position came from, and `ply` says where along that puzzle's line it sits
       -- provenance and a loose prior, not the difficulty of this puzzle. */
    e.source = p.source;
    out.push(e);
  });
  return out;
}

/* ------------------------------ cli ------------------------------ */

function arg(name, dflt) {
  const i = process.argv.indexOf(name);
  return i >= 0 && process.argv[i + 1] !== undefined ? process.argv[i + 1] : dflt;
}

if (require.main === module) {
  /* --inline already ran and exited near the top of this file, before the engine
     require, so there is deliberately no --inline branch here. */
  const opts = {
    games: parseInt(arg('--games', '2500'), 10),
    seed: parseInt(arg('--seed', '20260914'), 10),
    bias: parseFloat(arg('--bias', '0.5')),
    target: parseInt(arg('--target', '20'), 10),
    msBudget: parseInt(arg('--ms', '600000'), 10),
    /* The sweep runs until the RAREST family reaches --target, so the common
       ones overshoot hard: one 500-game run found 171 restraints while still
       waiting on 27 multisteps. Shipping all of them would make two thirds of
       the set a single family. --cap keeps the first N of each in discovery
       order, which is deterministic under a seed, and the yield block below
       records BOTH the true number found and the number kept -- capping the
       set never hides the measurement. */
    cap: parseInt(arg('--cap', '40'), 10)
  };
  const out = arg('--out', OUT_DEFAULT);
  /*
   * The survival family is NOT swept for. It is derived from the Lichess CC0
   * puzzle database by tools/lichess-seed.js and committed as a file, because
   * the positions have to come from real games: 1.9 million mate lines were
   * replayed to find 153 of them, which no playout from the opening is going to
   * stumble into. This stays the single writer of puzzles.json - it reads that
   * file rather than a second writer appending to the output.
   */
  const survivalPath = arg('--survival', path.join(ROOT, 'puzzles', 'survival-seed.json'));
  /* --now exists so "the same --seed reproduces a byte-identical puzzles.json"
     (M3-T1-AC6) is literally true and testable. Everything else in the output is
     a pure function of the seed; the wall-clock stamp was the one thing that was
     not, and without a way to pin it the criterion could never be checked. */
  const now = arg('--now', new Date().toISOString().replace(/\.\d+Z$/, 'Z'));
  /* The Lichess-seeded multistep puzzles, mined by tools/lichess-multistep.js.
     `--multistep none` skips them, which is how "the generator alone reproduces
     the sweep's puzzles" is checked without the seed in the way. */
  const multistepPath = arg('--multistep', path.join(ROOT, 'puzzles', 'multistep-seed.json'));

  /* A path the caller TYPED must exist. The two defaults may legitimately be
     absent -- a checkout from before the seed was built -- but an explicit
     argument that points nowhere used to be skipped in silence: exit 0 and a
     file missing every seeded puzzle, found only when a later test compared the
     committed data to the seed. (Found by deepcheck: a one-letter typo in
     --multistep produced exactly that.) */
  if (process.argv.indexOf('--survival') >= 0 && !fs.existsSync(survivalPath)) {
    throw new Error('--survival ' + survivalPath + ' does not exist');
  }
  if (process.argv.indexOf('--multistep') >= 0 && multistepPath !== 'none' && !fs.existsSync(multistepPath)) {
    throw new Error('--multistep ' + multistepPath + ' does not exist (pass "none" to skip it deliberately)');
  }

  const puzzles = [];
  const counts = {}, yield_ = {};

  /* Both seeds are read and DERIVED before the sweep, so a malformed or stale
     one fails in seconds rather than after a 200-second sweep is thrown away.
     (This comment used to say exactly that while the sweep ran first; the order
     now matches what it always claimed.) */
  let survival = [];
  if (fs.existsSync(survivalPath)) {
    const seed = JSON.parse(fs.readFileSync(survivalPath, 'utf8'));
    survival = (seed.puzzles || []).map(function (p, i) {
      const S = fen(p.fen);
      const ms = legal(S, true);
      /* RE-DERIVED, not copied. The seed file supplies a position and where it
         came from; everything a reader could check is recomputed here from the
         FEN, and the seed's own answer is used only to CONTRADICT this one if
         the two tools ever disagree. A stored depth would have been one more
         claim nobody verifies. */
      const r = trySurvival(S, 3, true);
      if (!r) throw new Error('survival seed ' + p.source.id +
        ': the position no longer satisfies the predicate — ' + p.fen);
      if (sqName(r.sole.from) + sqName(r.sole.to) + (r.sole.promo || '') !== p.solutionUci) {
        throw new Error('survival seed ' + p.source.id + ': seeder says ' + p.solutionUci +
          ', predicate says ' + sqName(r.sole.from) + sqName(r.sole.to));
      }
      const e = buildEntry('sur-' + String(i + 1).padStart(4, '0'), 'survival',
        S, [r.sole], ms, legal(S, false).length);
      /* CC0 asks for no attribution. The link is here because a position a
         reader can trace back to a real game is worth more than one that
         appeared from nowhere, and the Lichess rating is a difficulty prior no
         predicate in this repo can compute. */
      e.source = p.source;
      e.depth = r.depth;
      e.difficulty = r.depth === 3 ? 3 : (ms.length > 3 ? 3 : 2);
      /* The losing moves and what refutes each one, recomputed the same way. */
      /* Compared by square, NOT by object identity: trySurvival ran its own
         legal() call, so its move objects are different instances from the ones
         in `ms` and `m !== r.sole` is true even for the solution — which put the
         answer in its own decoy list until the validator caught it. */
      const soleKey = r.sole.from + ':' + r.sole.to + ':' + (r.sole.promo || '-');
      e.decoys = ms.filter(function (m) {
        return m.from + ':' + m.to + ':' + (m.promo || '-') !== soleKey;
      }).map(function (m) {
        const T = apply(S, m);
        const kill = legal(T, true).filter(function (x) {
          return legal(apply(T, x), true).length === 0 && inCheck(apply(T, x), apply(T, x).turn);
        })[0];
        return { uci: sqName(m.from) + sqName(m.to) + (m.promo || ''), san: san(S, m, true),
                 refutedBy: kill ? san(T, kill, true) : null };
      });
      return e;
    });
  }

  let multistepSeed = null, seeded = [];
  if (multistepPath !== 'none' && fs.existsSync(multistepPath)) {
    multistepSeed = JSON.parse(fs.readFileSync(multistepPath, 'utf8'));
    seeded = deriveMultistepSeeds(multistepSeed);
  }

  console.error('sweeping: games<=' + opts.games + ' seed=' + opts.seed + ' bias=' + opts.bias + ' target=' + opts.target + '/family');
  const r = sweep(opts);

  /* The one seed check that needs the sweep: a Lichess position must not also be
     a puzzle the playout found. Throws rather than dropping one, because a
     duplicate means the two sources overlap in a way nobody has looked at. */
  if (seeded.length) {
    const taken = new Set();
    FAMILIES.forEach(function (F) { r.found[F.name].forEach(function (p) { taken.add(p.fen); }); });
    seeded.forEach(function (p) {
      if (taken.has(p.fen)) throw new Error('multistep seed ' + p.source.id +
        ' is also found by the sweep -- ' + p.fen);
    });
  }

  FAMILIES.forEach(function (F) {
    const all = r.found[F.name];
    const got = all.slice(0, opts.cap);
    counts[F.name] = got.length;
    /* Measured yield, recorded either way (M3-T1-AC5). A family that comes up
       short says so here in a number; the predicate is never loosened to make
       the count look better. */
    yield_[F.name] = {
      found: all.length,
      kept: got.length,
      cap: opts.cap,
      target: opts.target,
      short: Math.max(0, opts.target - all.length),
      perThousandUnique: r.unique ? +(all.length / r.unique * 1000).toFixed(3) : 0
    };
    /* predicateSeconds deliberately does NOT go in the file. It is wall-clock,
       so writing it would break "the same --seed reproduces a byte-identical
       puzzles.json" (M3-T1-AC6) by two bytes and nothing else -- which is
       exactly how this was found. It is printed below instead. */
    got.forEach(function (p) { puzzles.push(p); });
    /* The Lichess-seeded puzzles are the same family and go straight after the
       sweep's, so the file stays grouped tactical, restraint, multistep,
       survival -- the order the page and tests/browser.js read it in. The
       family count includes them (the page and the validator count by family);
       the sweep's own yield above stays about the sweep, and the seed's is
       recorded beside it rather than blended in. */
    if (F.name === 'multistep' && seeded.length) {
      seeded.forEach(function (p) { puzzles.push(p); });
      counts.multistep = got.length + seeded.length;
      yield_.multistepSeeded = {
        kept: seeded.length,
        rowsScanned: multistepSeed.scan.rowsScanned,
        minReplies: multistepSeed.scan.minReplies,
        candidates: multistepSeed.selection.candidates
      };
    }
  });

  if (survival.length) {
    counts.survival = survival.length;
    yield_.survival = { found: survival.length, kept: survival.length, cap: survival.length,
      target: 0, short: 0, perThousandUnique: 0 };
    survival.forEach(function (p) { puzzles.push(p); });
  }

  const doc = {
    /* Schema 5 added `line` and a multistep `source`; schema 4 retired the
       escape family value and added survival with its source/depth fields. Each
       is bumped WITH the page reader in the same change -- and tests/puzzles.js
       reads SCHEMA from this file, so the generator and the committed data
       cannot silently disagree about which one they are. */
    schema: SCHEMA,
    generatedAt: now,
    generator: {
      strategy: 'check-biased playout from startState, depth-free predicates',
      familyPrecedence: FAMILIES.map(function (F) { return F.name; }).concat(survival.length ? ['survival'] : []),
      survivalSource: survival.length ? { file: path.basename(survivalPath), db: 'lichess-cc0' } : null,
      /* Only present when there is a seed, so a run without one produces the
         exact byte layout it always did. */
      ...(seeded.length ? { multistepSource: { file: path.basename(multistepPath), db: 'lichess-cc0' } } : {}),
      checkBias: opts.bias,
      games: r.games,
      positionsVisited: r.positions,
      uniquePositions: r.unique,
      seed: opts.seed,
      target: opts.target,
      yield: yield_,
      tool: 'tools/gen-puzzles.js'
    },
    counts: counts,
    puzzles: puzzles
  };
  fs.mkdirSync(path.dirname(out), { recursive: true });
  fs.writeFileSync(out, JSON.stringify(doc, null, 2) + '\n', 'utf8');

  console.error('games=' + r.games + ' positions=' + r.positions + ' unique=' + r.unique +
                ' in ' + (r.ms / 1000).toFixed(1) + 's');
  FAMILIES.forEach(function (F) {
    const y = yield_[F.name];
    console.error('  ' + F.name.padEnd(10) + y.kept + ' kept of ' + y.found + ' found, target ' + y.target +
      (y.short ? '  SHORT BY ' + y.short : '          ') +
      '  ' + y.perThousandUnique + '/1000 unique   ' +
      (r.predMs[F.name] / 1000).toFixed(1) + 's in the predicate');
  });
  console.error('wrote ' + out);
}

module.exports = { isMate, matesIn2, tryEscape, tryTactical, tryMultistep, tryRestraint, sweep, mulberry32,
                   SCHEMA, buildEntry, deriveMultistepSeeds };
